### ISSUE TITLE
Severe memory leak caused by endpoint discovery merge

### ISSUE THREAD

**Issue by i-chvets** [canonical/seldon-core-operator#123]
# Description
The fix for this issue needs to be merged into two branches:
Merge into:
- [x] `track/1.15` (release KF v1.7)
- [x] `main`

After this PR: https://github.com/canonical/seldon-core-operator/pull/94 every Seldon Deployment causes severe memory leak and Kubeflow deployment becomes unresponsive.
This was discovered when integration test for charm removal was introduced. Remove operation never succeeded and test failed with timeout errors.

Running integration tests with removal test produced errors:
```
unit-seldon-controller-manager-0: 20:37:58 ERROR unit.seldon-controller-manager/0.juju-log Uncaught exception while in charm code
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-seldon-controller-manager-0/charm/venv/ops/model.py", line 2615, in _run
    result = run(args, **kwargs)
  File "/usr/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '('/var/lib/juju/tools/unit-seldon-controller-manager-0/config-get', '--format=json')' returned non-zero exit status 1.
Traceback (most recent call last):
  File "./src/charm.py", line 549, in <module>
    main(SeldonCoreOperator)
  File "/var/lib/juju/agents/unit-seldon-controller-manager-0/charm/venv/ops/main.py", line 424, in main
    charm = charm_class(framework)
  File "./src/charm.py", line 65, in __init__
    self._metrics_port = self.model.config["metrics-port"]
  File "/var/lib/juju/agents/unit-seldon-controller-manager-0/charm/venv/ops/model.py", line 695, in __getitem__
    return self._data[key]
  File "/var/lib/juju/agents/unit-seldon-controller-manager-0/charm/venv/ops/model.py", line 679, in _data
    data = self._lazy_data = self._load()
  File "/var/lib/juju/agents/unit-seldon-controller-manager-0/charm/venv/ops/model.py", line 1519, in _load
    return self._backend.config_get()
  File "/var/lib/juju/agents/unit-seldon-controller-manager-0/charm/venv/ops/model.py", line 2727, in config_get
    out = self._run('config-get', return_output=True, use_json=True)
  File "/var/lib/juju/agents/unit-seldon-controller-manager-0/charm/venv/ops/model.py", line 2617, in _run
    raise ModelError(e.stderr)
ops.model.ModelError: ERROR permission denied
unit-seldon-controller-manager-0: 20:37:58 ERROR juju.worker.uniter.operation hook "stop" (via hook dispatching script: dispatch) failed: exit status 1
unit-seldon-controller-manager-0: 20:37:58 INFO juju.worker.uniter unit "seldon-controller-manager/0" shutting down: unit "seldon-controller-manager/0" not found (not found)
unit-prometheus-k8s-0: 20:40:01 INFO juju.worker.uniter.operation ran "update-status" hook (via hook dispatching script: dispatch)
controller-0: 20:40:56 INFO juju.worker.caasapplicationprovisioner.runner stopped "seldon-controller-manager", err: attempt count exceeded: try again
controller-0: 20:40:56 ERROR juju.worker.caasapplicationprovisioner.runner exited "seldon-controller-manager": attempt count exceeded: try again
controller-0: 20:40:56 INFO juju.worker.caasapplicationprovisioner.runner restarting "seldon-controller-manager" in 3s
controller-0: 20:40:59 INFO juju.worker.caasapplicationprovisioner.runner start "seldon-controller-manager"
ERROR lost connection to pod
```

**Comment by DnPlas** [comment]
> every Seldon Deployment causes severe memory leak and Kubeflow deployment becomes unresponsive.

What kind of logs/information you were getting to conclude it was causing a memory leak?

I see `ops.model.ModelError: ERROR permission denied` and `controller-0: 20:40:56 ERROR juju.worker.caasapplicationprovisioner.runner exited "seldon-controller-manager": attempt count exceeded: try again`, do you know where these errors are looking from?

**Comment by i-chvets** [comment]
Should be fixed by:
https://github.com/canonical/seldon-core-operator/issues/127
https://github.com/canonical/seldon-core-operator/pull/128

**Comment by i-chvets** [comment]
@simskij Merged updated libs. No memory leak, but processes are spawned/killed at high rate when Seldon Deployment is deployed.
```
$ ps ax | grep metrics_end
2312416 ?        Ss     0:00 /usr/bin/python3 lib/charms/observability_libs/v0/metrics_endpoint_discovery.py {"seldon-deployment-id": null} /usr/bin/juju-run seldon-controller-manager/0 /var/lib/juju/agents/unit-seldon-controller-manager-0/charm
2312552 ?        Sl     0:00 /usr/bin/juju-run -u seldon-controller-manager/0 JUJU_DISPATCH_PATH=hooks/metrics_endpoint_change /var/lib/juju/agents/unit-seldon-controller-manager-0/charm/dispatch

$ ps ax | grep metrics_end
2313578 ?        Ss     0:00 /usr/bin/python3 lib/charms/observability_libs/v0/metrics_endpoint_discovery.py {"seldon-deployment-id": null} /usr/bin/juju-run seldon-controller-manager/0 /var/lib/juju/agents/unit-seldon-controller-manager-0/charm
2313693 ?        Sl     0:00 /usr/bin/juju-run -u seldon-controller-manager/0 JUJU_DISPATCH_PATH=hooks/metrics_endpoint_change /var/lib/juju/agents/unit-seldon-controller-manager-0/charm/dispatch
2313733 ?        Rs     0:00 /usr/bin/python3 lib/charms/observability_libs/v0/metrics_endpoint_discovery.py {"seldon-deployment-id": null} /usr/bin/juju-run seldon-controller-manager/0 /var/lib/juju/agents/unit-seldon-controller-manager-0/charm

$ ps ax | grep metrics_end
2314072 ?        Ss     0:00 /usr/bin/python3 lib/charms/observability_libs/v0/metrics_endpoint_discovery.py {"seldon-deployment-id": null} /usr/bin/juju-run seldon-controller-manager/0 /var/lib/juju/agents/unit-seldon-controller-manager-0/charm
2314187 ?        Sl     0:00 /usr/bin/juju-run -u seldon-controller-manager/0 JUJU_DISPATCH_PATH=hooks/metrics_endpoint_change /var/lib/juju/agents/unit-seldon-controller-manager-0/charm/dispatch
2314226 ?        Rs     0:00 /usr/bin/python3 lib/charms/observability_libs/v0/metrics_endpoint_discovery.py {"seldon-deployment-id": null} /usr/bin/juju-run seldon-controller-manager/0 /var/lib/juju/agents/unit-seldon-controller-manager-0/charm
```

**Comment by simskij** [comment]
@i-chvets that is expected, as it kills and respawns the subprocess every time an event is being processed.

**Comment by NohaIhab** [comment]
backported to main by #130
